version: "3.8"

services:
  registry:
    image: registry:2
    restart: always
    # IMPORTANT : Le bloc "ports:" est supprimé ici. Le port 5000 est fermé de l'extérieur.
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - "{{ project_dir }}/data:/var/lib/registry"
      - "{{ project_dir }}/auth:/auth:ro"

  ui:
    image: joxit/docker-registry-ui:main
    restart: always
    # IMPORTANT : Le bloc "ports:" est supprimé ici aussi. L'UI passe par le proxy.
    environment:
      - REGISTRY_TITLE=Ansible Deployed Registry
      # Mise à jour demandée : pointage vers l'IP publique en HTTPS sur le port 443
      - REGISTRY_URL=https://{{ public_ip }}:443
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
    depends_on:
      - registry

  # AJOUT PHASE 2 : Le Reverse Proxy Nginx qui centralise et sécurise les flux
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "443:443" # Seul le port HTTPS est ouvert sur internet
      - "80:80" # Conservé uniquement pour la redirection HTTP -> HTTPS de Nginx
    volumes:
      # Montage de la configuration Nginx générée par Ansible
      - "{{ project_dir }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      # Montage des certificats SSL auto-signés générés à la volée
      - "{{ project_dir }}/certs:/etc/nginx/certs:ro"
    depends_on:
      - registry
      - ui
