name: Build, Test and Deploy React Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: npm ci, build and test
        run: |
          npm ci
          npm run jsdoc
          npm run build --if-present
          npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Setup Pages
        id: pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          if-no-files-found: error

      - name: Build and publish package on NPM
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          REMOTE_VERSION=$(npm view ci-cd-cours@$LOCAL_VERSION version 2>/dev/null || echo "")

          if [ "$REMOTE_VERSION" != "$LOCAL_VERSION" ]; then
            npm run build-npm-ci
            npm publish
          else
            echo "Version $LOCAL_VERSION already exists on npm. Skipping publish."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  test_docker_compose:
    runs-on: ubuntu-latest

    needs: build_test

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=ci_password" > .env
          echo "MYSQL_DATABASE=ynov_ci" >> .env
          echo "MYSQL_USER=root" >> .env
          echo "MYSQL_HOST=db" >> .env

      - name: Start Docker Compose and check services health
        run: docker compose up --build --wait --wait-timeout 180

      - name: Stop Docker Compose
        if: always()
        run: docker compose down -v

  deploy:
    runs-on: ubuntu-latest

    needs: build_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish_docker_images:
    runs-on: ubuntu-latest

    needs: test_docker_compose
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        run: |
          docker build -f Dockerfile.backend -t ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-cours-backend:latest .
          docker build -f Dockerfile.frontend -t ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-cours-frontend:latest .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-cours-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-cours-frontend:latest
